package openfl.filesystem;

#if (haxe4 && !flash && sys && (!flash_doc_gen || air_doc_gen))
import flight.FileSystem as FlightFileSystem;
import flight._internal._UInt8Array as FlightUInt8Array;
import haxe.Json;
import haxe.Serializer;
import haxe.Unserializer;
import haxe.io.Bytes;
import openfl.errors.Error;
import openfl.events.Event;
import openfl.events.EventDispatcher;
import openfl.filesystem.FileMode;
import openfl.errors.IOError;
import openfl.events.IOErrorEvent;
import openfl.net.ObjectEncoding;
import openfl.events.OutputProgressEvent;
import openfl.events.ProgressEvent;
import openfl.utils.ByteArray;
import openfl.utils.Endian;
import openfl.utils.IDataInput;
import openfl.utils.IDataOutput;
import openfl.utils.Object;

/**
	A FileStream object is used to read and write files. Files can be opened synchronously
	by calling the open() method or asynchronously by calling the openAsync() method.

	The advantage of opening files asynchronously is that other code can execute while Adobe
	AIR runs read and write processes in the background. When opened asynchronously, progress
	events are dispatched as operations proceed.

	A File object that is opened synchronously behaves much like a ByteArray object; a file
	opened asynchronously behaves much like a Socket or URLStream object. When a File object
	is opened synchronously, the caller pauses while the requested data is read from or written
	to the underlying file. When opened asynchronously, any data written to the stream is
	immediately buffered and later written to the file.

	Whether reading from a file synchronously or asynchronously, the actual read methods are
	synchronous. In both cases they read from data that is currently "available." The difference
	is that when reading synchronously all of the data is available at all times, and when
	reading asynchronously data becomes available gradually as the data streams into a read
	buffer. Either way, the data that can be synchronously read at the current moment is
	represented by the bytesAvailable property.

	An application that is processing asynchronous input typically registers for progress events
	and consumes the data as it becomes available by calling read methods. Alternatively, an
	application can simply wait until all of the data is available by registering for the complete
	event and processing the entire data set when the complete event is dispatched.

	@see [Workflow for reading and writing files](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/workflow-for-reading-and-writing-files.html)
	@see [FileStream open modes](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/filestream-open-modes.html)
	@see [Initializing a FileStream object, and opening and closing files](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/initializing-a-filestream-object-and-opening-and-closing-files.html)
	@see [The position property of a FileStream object](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/the-position-property-of-a-filestream-object.html)
	@see [The read buffer and the bytesAvailable property of a FileStream object](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/the-read-buffer-and-the-bytesavailable-property-of-a-filestream-object.html)
	@see [Asynchronous programming and the events generated by a FileStream object opened asynchronously](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/asynchronous-programming-and-the-events-generated-by-a-filestream-object-opened-asynchronously.html)
	@see [Data formats, and choosing the read and write methods to use](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/data-formats-and-choosing-the-read-and-write-methods-to-use.html)
	@see `openfl.filesystem.File`
**/
@:access(openfl.utils.ByteArray)
@:access(openfl.utils.ByteArrayData)
@:access(openfl.filesystem.File)
#if !openfl_debug
@:fileXml('tags="haxe,release"') @:noDebug
#end
class FileStream extends EventDispatcher implements IDataInput implements IDataOutput
{
	/**
		Returns the number of bytes of data available for reading in the input buffer. User code
		must call bytesAvailable to ensure that sufficient data is available before trying to read
		it with one of the read methods.

		@see [The read buffer and the bytesAvailable property of a FileStream object](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/the-read-buffer-and-the-bytesavailable-property-of-a-filestream-object.html)
	**/
	public var bytesAvailable(get, never):Int;

	/**
		The byte order for the data, either the BIG_ENDIAN or LITTLE_ENDIAN constant from the Endian
		class.
	**/
	public var endian(get, set):Endian;

	/**
		Specifies whether the HXSF, JSON, AMF3 or AMF0 format is used when writing or reading binary
		data by using the readObject() or writeObject() method.

		The value is a constant from the ObjectEncoding class. By default, on non-AIR platforms, the
		HXSF format is used. For AIR the default format is AMF3. If you would like to use AMF and AMF3
		on non-AIR platforms, you must also include the format dependency in your project from haxelib.

	**/
	public var objectEncoding:ObjectEncoding;

	/**
		The current position in the file.

		This value is modified in any of the following ways:

		* When you set the property explicitly
		* When reading from the FileStream object (by using one of the read methods)
		* When writing to the FileStream object

		The position is defined as a Number (instead of uint) in order to support files larger than
		232 bytes in length. The value of this property is always a whole number less than 253. If
		you set this value to a number with a fractional component, the value is rounded down to
		the nearest integer.

		When reading a file asyncronously, if you set the position property, the application begins
		filling the read buffer with the data starting at the specified position, and the bytesAvailable
		property may be set to 0. Wait for a complete event before using a read method to read data;
		or wait for a progress event and check the bytesAvailable property before using a read method.

		@see [The position property of a FileStream object](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/the-position-property-of-a-filestream-object.html)
	**/
	@:isVar public var position(get, set):UInt;

	/**
		The minimum amount of data to read from disk when reading files asynchronously.

		This property specifies how much data an asynchronous stream attempts to read beyond the current
		position. Data is read in blocks based on the file system page size. Thus if you set readAhead to
		9,000 on a computer system with an 8KB (8192 byte) page size, the runtime reads ahead 2 blocks,
		or 16384 bytes at a time. The default value of this property is infinity: by default a file that
		is opened to read asynchronously reads as far as the end of the file.

		Reading data from the read buffer does not change the value of the readAhead property. When you
		read data from the buffer, new data is read in to refill the read buffer.

		The readAhead property has no effect on a file that is opened synchronously.

		As data is read in asynchronously, the FileStream object dispatches progress events. In the event
		handler method for the progress event, check to see that the required number of bytes is available
		(by checking the bytesAvailable property), and then read the data from the read buffer by using a
		read method.
	**/
	public var readAhead:Float = Math.POSITIVE_INFINITY;

	/**
		The isWriting property returns a bool used to identify the write state of asynchronous Update,
		Append, or Write streams. If isWrite is true, data is actively being written from the buffer.
	**/
	public var isWriting(default, null):Bool = false;

	@:noCompletion private var __input:FlightFileStreamInput;
	@:noCompletion private var __output:FlightFileStreamOutput;
	@:noCompletion private var __fileMode:FileMode;
	@:noCompletion private var __file:File;
	@:noCompletion private var __isOpen:Bool;
	@:noCompletion private var __isWrite:Bool;
	@:noCompletion private var __openedAsync:Bool;
	@:noCompletion private var __pendingClose:Bool;
	@:noCompletion private var __positionDirty:Bool = false;
	@:noCompletion private var __buffer:ByteArray;
	@:noCompletion private var __openGeneration:Int = 0;
	@:noCompletion private var __openPending:Bool = false;
	@:noCompletion private var __writeInFlight:Bool = false;
	@:noCompletion private var __writeQueued:Bool = false;

	/**
		Creates a FileStream object. Use the open() or openAsync() method to open a file.
	**/
	public function new()
	{
		super();
		__isOpen = false;
		__openedAsync = false;
		isWriting = false;
		__pendingClose = false;

		objectEncoding = HXSF;
		position = 0;
	}

	/**
		 Closes the FileStream object.

		You cannot read or write any data after you call the close() method. If the file was
		opened asynchronously (the FileStream object used the openAsync() method to open the
		file), calling the close() method causes the object to dispatch the close event.

		Closing the application automatically closes all files associated with FileStream
		objects in the application. However, it is best to register for a closed event on
		all FileStream objects opened asynchronously that have pending data to write, before
		closing the application (to ensure that data is written).

		You can reuse the FileStream object by calling the open() or the openAsync() method.
		This closes any file associated with the FileStream object, but the object does not
		dispatch the close event.

		For a FileStream object opened asynchronously (by using the openAsync() method), even
		if you call the close() event for a FileStream object and delete properties and variables
		that reference the object, the FileStream object is not garbage collected as long as
		there are pending operations and event handlers are registered for their completion. In
		particular, an otherwise unreferenced FileStream object persists as long as any of the
		following are still possible:

		For file reading operations, the end of the file has not been reached (and the complete
		event has not been dispatched).
		Output data is still available to written, and output-related events (such as the
		outputProgress event or the ioError event) have registered event listeners.

		@event close    			The file, which was opened asynchronously, is closed.
	**/
	public function close():Void
	{
		if (!__isOpen)
		{
			if (__openPending)
			{
				__openPending = false;
				__openGeneration++;
			}
			return;
		}
		if (__pendingClose) return;
		if (__openedAsync && (__writeInFlight || __writeQueued))
		{
			__pendingClose = true;
			__startAsyncWrite();
			return;
		}
		__openGeneration++;
		__finishClose(__openedAsync);
	}

	/**
		Opens the FileStream object synchronously, pointing to the file specified by the
		file parameter.

		If the FileStream object is already open, calling the method closes the file before
		opening and no further events (including close) are delivered for the previously opened
		file.

		On systems that support file locking, a file opened in "write" or "update" mode
		(FileMode.WRITE or FileMode.UPDATE) is not readable until it is closed.

		Once you are done performing operations on the file, call the close() method of the
		FileStream object. Some operating systems limit the number of concurrently open files.

		@param 		file The File object specifying the file to open.
		@param 		fileMode A string from the FileMode class that defines the capabilities of the
					FileStream, such as the ability to read from or write to the file.
		@throws 	IOError The file does not exist; you do not have adequate permissions to
					open the file; you are opening a file for read access, and you do not have read
					permissions; or you are opening a file for write access, and you do not have write
					permissions.
		@throws 	SecurityError The file location is in the application directory, and the
					fileMode parameter is set to "append", "update", or "write" mode.

		@see https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/initializing-a-filestream-object-and-opening-and-closing-files.html
		@see https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/filestream-open-modes.html
	 */
	public function open(file:File, fileMode:FileMode):Void
	{
		if (file == null) throw new IOError("Invalid parameters.");
		__openPending = false;
		__openGeneration++;
		if (__isOpen) __finishClose(false);
		__file = file;
		__fileMode = fileMode;
		__openedAsync = false;
		__openFile();
	}

	/**
		Opens the FileStream object asynchronously, pointing to the file specified by the file
		parameter.

		If the FileStream object is already open, calling the method closes the file before opening
		and no further events (including close) are delivered for the previously opened file.

		If the fileMode parameter is set to FileMode.READ or FileMode.UPDATE, AIR reads data into
		the input buffer as soon as the file is opened, and progress and open events are dispatched
		as the data is read to the input buffer.

		On systems that support file locking, a file opened in "write" or "update" mode (FileMode.WRITE
		or FileMode.UPDATE) is not readable until it is closed.

		Once you are done performing operations on the file, call the close() method of the FileStream
		object. Some operating systems limit the number of concurrently open files.

		@param 		file The File object specifying the file to open.
		@param 		 A string from the FileMode class that defines the capabilities of the
					FileStream, such as the ability to read from or write to the file.
		@event 		ioError The file does not exist; you do not have adequate permissions to open the
					file; you are opening a file for read access, and you do not have read permissions; or you are
					opening a file for write access, and you do not have write permissions.
		@event 		progress Dispatched as data is read to the input buffer. (The file must be opened
					with the fileMode parameter set to FileMode.READ or FileMode.UPDATE.)
		@event		complete The file data has been read to the input buffer. (The file must be opened
					with the fileMode parameter set to FileMode.READ or FileMode.UPDATE.)
		@throws 	SecurityError The file location is in the application directory, and the
					fileMode parameter is set to "append", "update", or "write" mode.

		@see [Initializing a FileStream object, and opening and closing files](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/initializing-a-filestream-object-and-opening-and-closing-files.html)
		@see [FileStream open modes](https://books.openfl.org/openfl-developers-guide/working-with-the-file-system/filestream-open-modes.html)
	 */
	public function openAsync(file:File, fileMode:FileMode):Void
	{
		if (file == null)
		{
			dispatchEvent(new IOErrorEvent(IOErrorEvent.IO_ERROR, false, false, "Invalid parameters."));
			return;
		}
		if (__isOpen) __finishClose(false);
		__file = file;
		__fileMode = fileMode;
		__openedAsync = true;
		__pendingClose = false;
		var generation = ++__openGeneration;
		__openPending = true;
		if (fileMode != FileMode.READ)
		{
			try file.__ensureWritable() catch (error:Dynamic)
			{
				__dispatchAsyncError(error, generation);
				return;
			}
		}

		if (fileMode == FileMode.WRITE)
		{
			__prepareAsyncParent(generation, function():Void
			{
				var empty = new FlightUInt8Array(0);
				FlightFileSystem.writeBinaryFile(File.__getFlightFileSystemHost(), file.nativePath, empty).then(function(success:Bool):Bool
				{
					if (generation != __openGeneration) return success;
					if (!success) __dispatchAsyncError("Invalid parameters.", generation);
					else __finishAsyncOpen(empty, generation);
					return success;
				}, function(error:Dynamic):Bool
				{
					__dispatchAsyncError(error, generation);
					return false;
				});
			});
			return;
		}

		FlightFileSystem.readBinaryFile(File.__getFlightFileSystemHost(), file.nativePath).then(function(bytes:FlightUInt8Array):FlightUInt8Array
		{
			if (generation != __openGeneration) return bytes;
			if (bytes == null && fileMode == FileMode.READ)
			{
				__dispatchAsyncError("Invalid parameters.", generation);
			}
			else if (bytes == null)
			{
				__prepareAsyncParent(generation, function():Void
				{
					var empty = new FlightUInt8Array(0);
					FlightFileSystem.writeBinaryFile(File.__getFlightFileSystemHost(), file.nativePath, empty).then(function(success:Bool):Bool
					{
						if (success) __finishAsyncOpen(empty, generation); else __dispatchAsyncError("Invalid parameters.", generation);
						return success;
					}, function(error:Dynamic):Bool
					{
						__dispatchAsyncError(error, generation);
						return false;
					});
				});
			}
			else __finishAsyncOpen(bytes, generation);
			return bytes;
		}, function(error:Dynamic):FlightUInt8Array
		{
			__dispatchAsyncError(error, generation);
			return null;
		});
	}

	/**
	 * Reads a Boolean value from the file stream, byte stream, or byte array. A single byte is read
	 * and true is returned if the byte is nonzero, false otherwise.
	 *
	 * @return 		A Boolean value, true if the byte is nonzero, false otherwise.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readBoolean():Bool
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readByte() == 1;
	}

	/**
	 * Reads a signed byte from the file stream, byte stream, or byte array.
	 *
	 * @return The returned value is in the range -128 to 127.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 			EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readByte():Int
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readByte();
	}

	/**
	 * Reads the number of data bytes, specified by the length parameter, from the file stream, byte
	 * stream, or byte array. The bytes are read into the ByteArray objected specified by the bytes
	 * parameter, starting at the position specified by offset.
	 *
	 * @param	bytes
	 * @param	offset
	 * @param	length
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readBytes(bytes:ByteArray, offset:UInt = 0, length:UInt = 0):Void
	{
		__checkIfReadable();
		__buffer.readBytes(bytes, offset, length);
		__positionDirty = true;
	}

	/**
	 * Reads an IEEE 754 double-precision floating point number from the file stream, byte stream, or
	 * byte array.
	 *
	 * @return An IEEE 754 double-precision floating point number
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readDouble():Float
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readDouble();
	}

	/**
	 * Reads an IEEE 754 single-precision floating point number from the file stream, byte stream, or byte array.
	 *
	 * @return		An IEEE 754 single-precision floating point number.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readFloat():Float
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readFloat();
	}

	/**
	 * Reads a signed 32-bit integer from the file stream, byte stream, or byte array.
	 *
	 * @return The returned value is in the range -2147483648 to 2147483647.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readInt():Int
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readInt32();
	}

	/**
	 * Reads a multibyte string of specified length from the file stream, byte stream, or byte array using
	 * the specified character set.
	 *
	 * @param		length The number of bytes from the byte stream to read.
	 * @param		charSet The string denoting the character set to use to interpret the bytes. Possible
	 * character set strings include "shift-jis", "cn-gb", "iso-8859-1", and others.	 *
	 * @return		UTF-8 encoded string.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readMultiByte(length:Int, charSet:String):String
	{
		__checkIfReadable();
		__positionDirty = true;
		return readUTFBytes(length);
	}

	/**
	 * Reads an object from the file stream, byte stream, or byte array, encoded in AMF serialized format.
	 *
	 * @return The deserialized object
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readObject():Dynamic
	{
		__checkIfReadable();

		switch (objectEncoding)
		{
			case AMF0, AMF3:
				// Flight has no public AMF codec; see agents/flight-gaps.md.
				throw new Error("AMF object decoding is not available");

			case HXSF:
				var data = readUTF();
				return Unserializer.run(data);

			case JSON:
				var data = readUTF();
				return Json.parse(data);

			default:
				return null;
		}

		__positionDirty = true;
		return {};
	}

	/**
	 * Reads a signed 16-bit integer from the file stream, byte stream, or byte array.
	 *
	 * @return The returned value is in the range -32768 to 32767.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readShort():Int
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readInt16();
	}

	/**
	 * Reads an unsigned byte from the file stream, byte stream, or byte array.
	 *
	 * @return The returned value is in the range 0 to 255.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readUnsignedByte():UInt
	{
		__checkIfReadable();
		__positionDirty = true;
		return ByteArray.fromBytes(__input.read(1)).readUnsignedByte();
	}

	/**
	 * Reads an unsigned 32-bit integer from the file stream, byte stream, or byte array.
	 *
	 * @return The returned value is in the range 0 to 4294967295.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readUnsignedInt():UInt
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readInt32();
	}

	/**
	 * Reads an unsigned 16-bit integer from the file stream, byte stream, or byte array.
	 *
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readUnsignedShort():UInt
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readUInt16();
	}

	/**
		* Reads a UTF-8 string from the file stream, byte stream, or byte array. The string is assumed to be
		* prefixed with an unsigned short indicating the length in bytes.

		This method is similar to the readUTF() method in the Java® IDataInput interface.

		* @return A UTF-8 string produced by the byte representation of characters.
		* @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
		* for files opened for asynchronous operations (by using the openAsync() method).
		* @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
		* with read capabilities; or for a file that has been opened for synchronous operations (by using
		* the open() method), the file cannot be read (for example, because the file is missing).
		* @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
		* (specified by the bytesAvailable property).
	 */
	public function readUTF():String
	{
		__checkIfReadable();
		__positionDirty = true;
		var length:Int = __input.readUInt16();
		return __input.readString(length);
	}

	/**
	 * Reads a sequence of UTF-8 bytes from the byte stream or byte array and returns a string.
	 * @param		length The number of bytes to read.
	 * @return A UTF-8 string produced by the byte representation of characters of the specified length.
	 * @event 		ioError The file cannot be read or the file is not open. This event is dispatched only
	 * for files opened for asynchronous operations (by using the openAsync() method).
	 * @throws 		IOError The file has not been opened; the file has been opened, but it was not opened
	 * with read capabilities; or for a file that has been opened for synchronous operations (by using
	 * the open() method), the file cannot be read (for example, because the file is missing).
	 * @throws 		EOFError The position specfied for reading data exceeds the number of bytes available
	 * (specified by the bytesAvailable property).
	 */
	public function readUTFBytes(length:Int):String
	{
		__checkIfReadable();
		__positionDirty = true;
		return __input.readString(length);
	}

	/**
	 * Truncates the file at the position specified by the position property of the FileStream object.
	 *
	 * Bytes from the position specified by the position property to the end of the file are deleted.
	 * The file must be open for writing.
	 * @throws 		IllegalOperationError The file is not open for writing.
	 */
	public function truncate():Void
	{
		__checkIfOpen();
		var targetPosition = position;
		__buffer.length = targetPosition;
		__buffer.position = targetPosition;
		__onOutputChanged();
		position = targetPosition;
		__file.__fileStatsDirty = true;
	}

	/**
	 * Writes a Boolean value. A single byte is written according to the value parameter, either
	 * 1 if true or 0 if false.
	 *
	 * @param		value  A Boolean value determining which byte is written. If the parameter is
	 * true, 1 is written; if false, 0 is written.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeBoolean(value:Bool):Void
	{
		__checkIfWritable();
		__output.writeByte(value ? 1 : 0);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a byte. The low 8 bits of the parameter are used; the high 24 bits are ignored.
	 *
	 * @param	value A byte value as an integer.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeByte(value:Int):Void
	{
		__checkIfWritable();
		__output.writeByte(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 *  Writes a sequence of bytes from the specified byte array, bytes, starting at the byte specified
	 * by offset (using a zero-based index) with a length specified by length, into the file stream,
	 * byte stream, or byte array.
	 *
	 * If the length parameter is omitted, the default length of 0 is used and the entire buffer starting at
	 * offset is written. If the offset parameter is also omitted, the entire buffer is written.
	 *
	 * If the offset or length parameter is out of range, they are clamped to the beginning and end of the bytes array.
	 *
	 * @param		bytes The byte array to write.
	 * @param		offset A zero-based index specifying the position into the array to begin writing.
	 * @param		length An unsigned integer specifying how far into the buffer to write.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeBytes(bytes:ByteArray, offset:Int = 0, length:Int = 0):Void
	{
		__checkIfWritable();
		__buffer.writeBytes(bytes, offset, length);
		__onOutputChanged();
	}

	/**
	 * Writes an IEEE 754 double-precision (64-bit) floating point number.
	 *
	 * @param		value A double-precision (64-bit) floating point number.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeDouble(value:Float):Void
	{
		__checkIfWritable();
		__output.writeDouble(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes an IEEE 754 single-precision (32-bit) floating point number.
	 *
	 * @param		A single-precision (32-bit) floating point number.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeFloat(value:Float):Void
	{
		__checkIfWritable();
		__output.writeFloat(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a 32-bit signed integer.
	 *
	 * @param		value A byte value as a signed integer
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeInt(value:Int):Void
	{
		__checkIfWritable();
		__output.writeInt32(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a multibyte string to the file stream, byte stream, or byte array, using the specified
	 * character set.
	 *
	 * @param		value The string value to be written.
	 * @param		charSet The string denoting the character set to use. Possible character set strings
	 * include "shift-jis", "cn-gb", "iso-8859-1", and others
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeMultiByte(value:String, charSet:String):Void
	{
		__checkIfWritable();
		writeUTFBytes(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes an object to the file stream, byte stream, or byte array, in AMF, HXSF, or JSON serialized
	 * format. The format library from haxelib is required to enable AMF on non-AIR targets.
	 *
	 * @param		object The object to be serialized.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeObject(object:Dynamic):Void
	{
		__checkIfWritable();
		__writeObject(object);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a 16-bit integer. The low 16 bits of the parameter are used; the high 16 bits are ignored.
	 *
	 * @param		value  A byte value as an integer.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeShort(value:Int):Void
	{
		__checkIfWritable();
		__output.writeInt16(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a 32-bit unsigned integer.
	 *
	 * @param		value A byte value as an unsigned integer.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeUnsignedInt(value:UInt):Void
	{
		__checkIfWritable();
		__output.writeInt32(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a UTF-8 string to the file stream, byte stream, or byte array. The length of
	 * the UTF-8 string in bytes is written first, as a 16-bit integer, followed by the bytes
	 * representing the characters of the string.
	 * @param		value The string value to be written.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		RangeError — If the length of the string is larger than 65535.
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeUTF(value:String):Void
	{
		__checkIfWritable();
		__output.writeInt16(value.length);
		__output.writeString(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	/**
	 * Writes a UTF-8 string. Similar to writeUTF(), but does not prefix the string with a 16-bit length
	 * integer.
	 *
	 * @param		value The string value to be written.
	 * @event 		ioError  You cannot write to the file (for example, because the file is missing).
	 * This event is dispatched only for files that have been opened for asynchronous operations (by
	 * using the openAsync() method).
	 * @throws 		The file has not been opened; the file has been opened, but it was not opened
	 * with write capabilities; or for a file that has been opened for synchronous operations (by
	 * using the open() method), the file cannot be written (for example, because the file is missing).
	 */
	public function writeUTFBytes(value:String):Void
	{
		__checkIfWritable();
		__output.writeString(value);
		__file.__fileStatsDirty = true;
		__positionDirty = true;
	}

	@:noCompletion private function __checkIfOpen():Void
	{
		if (!__isOpen)
		{
			throw new Error("This FileStream object does not have a stream opened.", 2092);
		}
	}

	@:noCompletion private function __checkIfReadable():Void
	{
		__checkIfOpen();

		if (__isWrite)
		{
			throw new Error("This FileStream object does not have a input stream opened.", 2092);
		}
	}

	@:noCompletion private function __checkIfWritable():Void
	{
		__checkIfOpen();

		if (!__isWrite)
		{
			throw new Error("This FileStream object does not have a output stream opened.", 2092);
		}
	}

	@:noCompletion private function __getStreamBytesAvailable():Int
	{
		return __buffer == null ? 0 : __buffer.length - __buffer.position;
	}

	@:noCompletion private function __openFile():Void
	{
		try
		{
			var bytes:FlightUInt8Array = null;
			var existed = __file.exists;
			if (__fileMode != FileMode.WRITE)
			{
				bytes = File.__resolveFlight(FlightFileSystem.readBinaryFile(File.__getFlightFileSystemHost(), __file.nativePath), null);
			}
			if (__fileMode == FileMode.READ && bytes == null) throw new IOError("Invalid parameters.");
			if (__fileMode != FileMode.READ && __fileMode != FileMode.WRITE && existed && bytes == null)
			{
				throw new IOError("Invalid parameters.");
			}

			if (__fileMode != FileMode.READ)
			{
				__file.__ensureWritable();
				__ensureParentSync();
			}

			if (bytes == null) bytes = new FlightUInt8Array(0);
			__initializeBuffer(bytes);
			if (__fileMode == FileMode.WRITE || ((__fileMode == FileMode.APPEND || __fileMode == FileMode.UPDATE) && !existed))
			{
				__flushSync();
			}
		}
		catch (error:Dynamic)
		{
			__isOpen = false;
			__buffer = null;
			throw Std.isOfType(error, IOError) ? error : new IOError("Invalid parameters.");
		}
	}

	@:noCompletion private function __dispatchAsyncError(error:Dynamic, generation:Int):Void
	{
		if (generation != __openGeneration) return;
		__openPending = false;
		__isOpen = false;
		__writeInFlight = false;
		__writeQueued = false;
		isWriting = false;
		dispatchEvent(new IOErrorEvent(IOErrorEvent.IO_ERROR, false, false, Std.string(error)));
	}

	@:noCompletion private function __ensureParentSync():Void
	{
		var parent = __file.parent;
		if (parent != null && !parent.exists) parent.createDirectory();
	}

	@:noCompletion private function __finishAsyncOpen(bytes:FlightUInt8Array, generation:Int):Void
	{
		if (generation != __openGeneration) return;
		__openPending = false;
		__initializeBuffer(bytes);
		__openedAsync = true;
		dispatchEvent(new Event(Event.OPEN));
		if (generation != __openGeneration || !__isOpen) return;
		if (__fileMode == FileMode.READ)
		{
			var length = __buffer.length;
			dispatchEvent(new ProgressEvent(ProgressEvent.PROGRESS, false, false, length, length));
			if (generation == __openGeneration && __isOpen) dispatchEvent(new Event(Event.COMPLETE));
		}
	}

	@:noCompletion private function __finishClose(dispatchClose:Bool):Void
	{
		var wasOpen = __isOpen;
		__isOpen = false;
		__openedAsync = false;
		__pendingClose = false;
		__openPending = false;
		__writeInFlight = false;
		__writeQueued = false;
		isWriting = false;
		if (__input != null) __input.close();
		if (__output != null) __output.close();
		__input = null;
		__output = null;
		__buffer = null;
		position = 0;
		__positionDirty = false;
		if (wasOpen && dispatchClose) dispatchEvent(new Event(Event.CLOSE));
	}

	@:noCompletion private function __flightBufferBytes():FlightUInt8Array
	{
		var bytes = new FlightUInt8Array(__buffer == null ? 0 : __buffer.length);
		if (__buffer != null) for (index in 0...__buffer.length) bytes[index] = __buffer[index];
		return bytes;
	}

	@:noCompletion private function __flushSync():Void
	{
		if (!File.__resolveFlight(FlightFileSystem.writeBinaryFile(File.__getFlightFileSystemHost(), __file.nativePath, __flightBufferBytes()), false))
		{
			throw new IOError("Invalid parameters.");
		}
	}

	@:noCompletion private function __initializeBuffer(bytes:FlightUInt8Array):Void
	{
		var source = Bytes.alloc(bytes.length);
		for (index in 0...bytes.length) source.set(index, bytes[index]);
		__buffer = ByteArray.fromBytes(source);
		__buffer.endian = BIG_ENDIAN;
		__isWrite = __fileMode != FileMode.READ;
		__isOpen = true;
		__positionDirty = false;
		__input = __isWrite ? null : new FlightFileStreamInput(__buffer);
		__output = __isWrite ? new FlightFileStreamOutput(__buffer, __onOutputChanged) : null;
		var initialPosition = __fileMode == FileMode.APPEND ? __buffer.length : 0;
		position = __fileMode == FileMode.APPEND ? 0 : initialPosition;
		__buffer.position = initialPosition;
	}

	@:noCompletion private function __onOutputChanged():Void
	{
		__file.__fileStatsDirty = true;
		__positionDirty = true;
		if (__openedAsync)
		{
			__writeQueued = true;
			isWriting = true;
			__startAsyncWrite();
		}
		else __flushSync();
	}

	@:noCompletion private function __prepareAsyncParent(generation:Int, complete:Void->Void):Void
	{
		var parent = __file.parent;
		if (parent == null)
		{
			complete();
			return;
		}
		FlightFileSystem.makeDirectory(File.__getFlightFileSystemHost(), parent.nativePath).then(function(success:Bool):Bool
		{
			if (generation != __openGeneration) return success;
			if (success) complete(); else __dispatchAsyncError("Invalid parameters.", generation);
			return success;
		}, function(error:Dynamic):Bool
		{
			__dispatchAsyncError(error, generation);
			return false;
		});
	}

	@:noCompletion private function __startAsyncWrite():Void
	{
		if (!__openedAsync || __writeInFlight || !__writeQueued) return;
		var generation = __openGeneration;
		var bytes = __flightBufferBytes();
		__writeQueued = false;
		__writeInFlight = true;
		FlightFileSystem.writeBinaryFile(File.__getFlightFileSystemHost(), __file.nativePath, bytes).then(function(success:Bool):Bool
		{
			if (generation != __openGeneration) return success;
			__writeInFlight = false;
			if (!success)
			{
				__dispatchAsyncWriteError("Invalid parameters.", generation);
				return false;
			}
			dispatchEvent(new OutputProgressEvent(OutputProgressEvent.OUTPUT_PROGRESS, false, false, 0, bytes.length));
			if (__writeQueued) __startAsyncWrite();
			else if (!__writeInFlight)
			{
				isWriting = false;
				if (__pendingClose) __finishClose(true);
			}
			return true;
		}, function(error:Dynamic):Bool
		{
			__writeInFlight = false;
			__dispatchAsyncWriteError(error, generation);
			return false;
		});
	}

	@:noCompletion private function __dispatchAsyncWriteError(error:Dynamic, generation:Int):Void
	{
		if (generation != __openGeneration) return;
		__writeInFlight = false;
		__writeQueued = false;
		isWriting = false;
		dispatchEvent(new IOErrorEvent(IOErrorEvent.IO_ERROR, false, false, Std.string(error)));
		if (generation == __openGeneration && __pendingClose && !__writeInFlight && !__writeQueued) __finishClose(true);
	}

	@:noCompletion private function __writeObject(object:Dynamic):Void
	{
		switch (objectEncoding)
		{
			case AMF0, AMF3:
				// Flight has no public AMF codec; see agents/flight-gaps.md.
				throw new Error("AMF object encoding is not available");

			case HXSF:
				var value = Serializer.run(object);
				writeUTF(value);

			case JSON:
				var value = Json.stringify(object);
				writeUTF(value);

			default:
				return;
		}
	}

	@:noCompletion private function get_endian():Endian
	{
		if (__isWrite)
		{
			return __output.bigEndian ? BIG_ENDIAN : LITTLE_ENDIAN;
		}

		return __input.bigEndian ? BIG_ENDIAN : LITTLE_ENDIAN;
	}

	@:noCompletion private function set_endian(value:Endian):Endian
	{
		if (__isWrite)
		{
			__output.bigEndian = value == BIG_ENDIAN ? true : false;
			return value;
		}

		__input.bigEndian = value == BIG_ENDIAN ? true : false;
		return value;
	}

	@:noCompletion private function get_bytesAvailable():Int
	{
		return __isOpen ? __getStreamBytesAvailable() : 0;
	}

	@:noCompletion private function get_position():UInt
	{
		if (__positionDirty && __buffer != null)
		{
			__positionDirty = false;
			position = __buffer.position;
		}
		return position;
	}

	@:noCompletion private function set_position(value:UInt):UInt
	{
		if (__isOpen && __buffer != null) __buffer.position = value;

		return position = value;
	}
}

@:noCompletion private class FlightFileStreamInput
{
	public var bigEndian(get, set):Bool;
	private var buffer:ByteArray;

	public function new(buffer:ByteArray)
	{
		this.buffer = buffer;
	}

	public function close():Void {}
	public function read(length:Int):Bytes
	{
		var result = Bytes.alloc(length);
		readBytes(result, 0, length);
		return result;
	}
	public function readByte():Int return buffer.readUnsignedByte();
	public function readBytes(bytes:Bytes, offset:Int, length:Int):Int
	{
		for (index in 0...length) bytes.set(offset + index, buffer.readUnsignedByte());
		return length;
	}
	public function readDouble():Float return buffer.readDouble();
	public function readFloat():Float return buffer.readFloat();
	public function readInt16():Int return buffer.readShort();
	public function readInt32():Int return buffer.readInt();
	public function readString(length:Int):String return buffer.readUTFBytes(length);
	public function readUInt16():Int return buffer.readUnsignedShort();
	private function get_bigEndian():Bool return buffer.endian == BIG_ENDIAN;
	private function set_bigEndian(value:Bool):Bool
	{
		buffer.endian = value ? BIG_ENDIAN : LITTLE_ENDIAN;
		return value;
	}
}

@:noCompletion private class FlightFileStreamOutput
{
	public var bigEndian(get, set):Bool;
	private var buffer:ByteArray;
	private var changed:Void->Void;

	public function new(buffer:ByteArray, changed:Void->Void)
	{
		this.buffer = buffer;
		this.changed = changed;
	}

	public function close():Void {}
	public function writeByte(value:Int):Void
	{
		buffer.writeByte(value);
		changed();
	}
	public function writeDouble(value:Float):Void
	{
		buffer.writeDouble(value);
		changed();
	}
	public function writeFloat(value:Float):Void
	{
		buffer.writeFloat(value);
		changed();
	}
	public function writeInt16(value:Int):Void
	{
		buffer.writeShort(value);
		changed();
	}
	public function writeInt32(value:Int):Void
	{
		buffer.writeInt(value);
		changed();
	}
	public function writeString(value:String):Void
	{
		buffer.writeUTFBytes(value);
		changed();
	}
	private function get_bigEndian():Bool return buffer.endian == BIG_ENDIAN;
	private function set_bigEndian(value:Bool):Bool
	{
		buffer.endian = value ? BIG_ENDIAN : LITTLE_ENDIAN;
		return value;
	}
}

#elseif flash
#if air
typedef FileStream = flash.filesystem.FileStream;
#end
#end
